### ISSUE TITLE
Can't build icrystal

### ISSUE THREAD

**Issue by kojix2** [RomainFranceschini/icrystal#2]
I tried to use icrystal, but I couldn't.

```
shards build
```

Error message

```
Dependencies are satisfied
Building: icrystal
Error target icrystal failed to compile:
Error: file 'bin/icrystal.cr' does not exist
```

The target file does not exist.

https://github.com/RomainFranceschini/icrystal/blob/08764f7a09c6e5c3363965c46f573bb5a349cbd7/shard.yml#L19-L21

Probably because `.gitignore` prevent files from being uploaded to the bin directory.

https://github.com/RomainFranceschini/icrystal/blob/08764f7a09c6e5c3363965c46f573bb5a349cbd7/.gitignore#L1-L9

FInally, I edit `src/icrystal` as a workaround.

```
require "./icrystal/**"

module ICrystal
  VERSION = "0.1.0"
end

ICrystal::Command.run
```
And change build target to `src/icrystal`. And it works fine.
I'm not familiar with icrystal, so I don't know if this is a good way to go. Some people may want to use icrystal as a library, and for those people I don't think it's a good idea for icrystal to call commands at any time.

**Comment by kojix2** [comment]
I add `cli.cr`.
Any ideas?

**Comment by RomainFranceschini** [comment]
Thank you @kojix2, I indeed missed this rule in the `.gitignore`
